language: php
dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --no-interaction --no-progress --no-suggest --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]
    then
      php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
    fi
